packages:
  - 'packages/*'

catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  '@types/webxr': ^0.5.0
  typescript: ^5.2.2
  tsup: ^8.0.0
  vite: ^7.2.7
  '@vitejs/plugin-react': ^4.2.1
  vitest: ^2.1.0
  '@vitest/coverage-v8': ^2.1.0
  '@testing-library/react': ^16.0.0
  '@testing-library/jest-dom': ^6.4.0
  '@testing-library/user-event': ^14.5.0
  jsdom: ^24.1.0
